# Generated by Django 5.1.3 on 2024-11-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
